#!/bin/bash

INFO='\e[1m\e[93m'
ERROR='\e[1m\e[31m'
SUCCESS='\e[1m\e[32m'
TEXT='\e[0m\e[1m\e[37m'
CLEARC='\e[0m'
ARG='\e[34m'
PKG='\e[35m'

WORKDIR="$HOME/.aurman"

exec 2> /dev/null

echo -e "\e[1m\e[94mA\e[93mU\e[97mRM\e[93mA\e[94mN${CLEARC} \e[1m\e[37mby Kocotian v0.2.1${CLEARC}"

if [ $1 == '-S' ]
then
	if [ ! -z ${2+x} ]
	then
		if [ ! -d "$WORKDIR/pkgs" ]
		then
			echo -e "${INFO}==>${TEXT} Creating working directory for aurman${CLEARC}"
			mkdir -p "$WORKDIR/pkgs"
		fi
		cd "$WORKDIR/pkgs"
		echo -e "${INFO}==>${TEXT} Cloning ${PKG}$2${TEXT} package data${CLEARC}"
		exec 2> /dev/stdout
		echo -e "${TEXT}"
		git clone https://aur.archlinux.org/$2.git
		exec 2> /dev/null
		echo -e "${CLEARC}"
		echo -e "${SUCCESS}==>${TEXT} Package data cloned${CLEARC}"
		cd $2
		if [ -z ${3+x} ]
		then
			echo -e "${INFO}==>${TEXT} ${PKG}$2${TEXT} package make started${CLEARC}"
			exec 2> /dev/stdout
			makepkg -si
			exec 2> /dev/null
		else
			echo -e "${INFO}==>${TEXT} ${PKG}$2${TEXT} package make started with custom settings ${ARG}$3${CLEARC}"
			exec 2> /dev/stdout
			makepkg $3
			exec 2> /dev/null
		fi
	else
		echo "Usage: aurman -S <package name>"
	fi
elif [ $1 == "-C" ]
then
	echo -e "${INFO}==>${TEXT} Cleaning cache...${CLEARC}"
	if [ -d "$WORKDIR/pkgs" ]
	then
		rm "$WORKDIR/pkgs" -r
	fi
	echo -e "${SUCCESS}==>${TEXT} Cache cleaned!${CLEARC}"
else
	echo "AURMAN is a simple tool wrote in bash that will help you with AUR experience
Usage:
    aurman -S  <package name> [arg] - clone, make and install package from default AUR repository (aur.archlinux.org), [arg] is arguments for makepkg
    aurman -C                       - clear aurman cache (removing packages)
    aurman -h                       - display this usage"
fi
